#!/bin/bash

# Make sure the user data directory is owned by the developer user
if [ -d /home/mule/.eclipse ]; then
  sudo chown mule:mule /home/developer/.eclipse
fi
exec /opt/AnypointStudio/AnypointStudio
